var ERR_FLASH_DUR = 800;

var TIME_BETWEEN_DOUBLE_CLICK = 200;

var INTERVAL_LEVEL_COUNTER_UPDATE = 1000;

var MAX_LEVEL_RANDTICK = 3;

var PROB_RANDTICK_TILE_EMPTY            = 0.1;
var PROB_RANDTICK_TILE_RANDTICK_SPAWNED = 1;
